In [1]:
import numpy as np
arr=np.array([45,7,3,18,23,24,16])
res=np.flip (arr[-7:-1])
print('reverse of the data')
print(res)

reverse of the data
[24 23 18  3  7 45]


In [21]:
import numpy as np
arr=np.array([[5,3,7],[13,24,16]])
arr1=np.array([[18,24,7],[30,17,24]])
con=np.concatenate((arr,arr1),axis=0)
print('concatenated 2 arrays using axis:',con)

concatenated 2 arrays using axis: [[ 5  3  7]
 [13 24 16]
 [18 24  7]
 [30 17 24]]


In [43]:
import numpy as np
arr=np.array([[3,1,6],[9,16,24]])
arr1=np.array([[18,77,45],[33,7,5]])
con=np.concatenate((arr,arr1),axis=1)
print('concatenated 2 array:',con)

concatenated 2 array: [[ 3  1  6 18 77 45]
 [ 9 16 24 33  7  5]]


In [35]:
import numpy as np
arr=np.array([5,1,7,6,3])
arr1=np.array([16,17,23,24,20])
con=np.concatenate([arr,arr1])
print('using concatenate to join two array')
print('concatenate two array arr:',con)

using concatenate to join two array
concatenate two array arr: [ 5  1  7  6  3 16 17 23 24 20]
